# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20161102_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/question.jpg', null=True, upload_to='images/'),
        ),
    ]
